language: ruby
rvm:
  - 2.3.1
cache: bundler
env:
  global:
    # GH_TOKEN=xxxxxxxxxxxxxxxxxx
    - secure: "a+FFKITeUmzikEMNGyH35eiGBKcUDaHONHMPsjsEzYIq+uyyiXAI9VoJTNs3wr5eT7dbPPy3Mk6QQhE3sA0IS7J7ZmMyvQjHC/fWrPc/MPqG7/Byff6OtCo3Ma02AvEJUCLBIQ+NXFuV/pyJ18zU08b6EDZgy1qL681wSMHfK38="
script:
  - bundle exec middleman build
after_success:
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then ./scripts/deploy.sh; fi
